---
- name: Min Password Length and Disable USB
  hosts: [windows]
  tasks:
    - name: Minimum Password Length
      ansible.windows.win_shell: |
        Set-ADDefaultDomainPasswordPolicy -Identity (Get-ADDomain).DistinguishedName -MinPasswordLength 12
      register: password_length_result

    - name: Display Password Length
      ansible.builtin.debug:
        var: password_length_result.stdout_lines

    - name: Verify Minimum Password
      ansible.windows.win_shell: |
        (Get-ADDefaultDomainPasswordPolicy).MinPasswordLength
      register: verify_password_length

    - name: Display Verification
      ansible.builtin.debug:
        var: verify_password_length.stdout_lines

    - name: Disable USB
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR
        name: Start
        data: 4
        type: dword

    - name: Verify USB
      ansible.windows.win_shell: |
        Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR" -Name "Start"
      register: verify_usb_disabled

    - name: USB Disabled Verification
      ansible.builtin.debug:
        var: verify_usb_disabled.stdout_lines
