---
- name: Backup Configuration Files and Update System Packages
  hosts: all
  become: yes
  tasks:
    # Backup Configuration Files
    - name: Backup sshd_config on Linux
      ansible.builtin.copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.backup
        remote_src: yes
      when: ansible_os_family == "Rocky"

    - name: Backup hosts file on Windows
      ansible.windows.win_copy:
        src: C:\Windows\System32\drivers\etc\hosts
        dest: C:\Windows\System32\drivers\etc\hosts.backup
        remote_src: yes
      when: ansible_os_family == "Windows"

    # Update System Packages
    - name: Update packages on Linux (excluding kernel)
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: kernel*
      when: ansible_os_family == "Rocky"

    - name: Install critical Windows updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
        state: installed
      when: ansible_os_family == "Windows"
