---
- name: Backup and Update Linux Servers
  hosts: linux
  become: yes
  tasks:
    - name: Backup sshd_config
      ansible.builtin.copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.backup
        remote_src: yes

    - name: Update packages excluding kernel
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: kernel*

- name: Backup and Update Windows Servers  
  hosts: windows
  tasks:
    - name: Backup hosts file
      ansible.windows.win_copy:
        src: C:\Windows\System32\drivers\etc\hosts
        dest: C:\Windows\System32\drivers\etc\hosts.backup
        remote_src: yes

    - name: Install critical Windows updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
        state: installed
