---
- name: Backup and Verify Disk Usage Linux Servers
  hosts: linux
  become: yes
  tasks:
    - name: Backup sshd_config
      ansible.builtin.copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.backup
        remote_src: yes

     - name: Run df -h on Linux servers
      ansible.builtin.shell: df -h
      register: disk_usage

    - name: Display Linux disk usage
      ansible.builtin.debug:
        var: disk_usage.stdout_lines

  - name: Backup and Verify Disk Usage Windows Servers  
  hosts: windows
  tasks:
    - name: Backup hosts file
      ansible.windows.win_copy:
        src: C:\Windows\System32\drivers\etc\hosts
        dest: C:\Windows\System32\drivers\etc\hosts.backup
        remote_src: yes

    - name: Run Get-PSDrive on Windows servers
      ansible.windows.win_shell: |
        Get-PSDrive -PSProvider 'FileSystem' | Select-Object Name, @{Name="UsedGB";Expression={[math]::Round($_.Used/1GB, 2)}}, @{Name="FreeGB";Expression={[math]::Round($_.Free/1GB, 2)}}
      register: disk_usage

    - name: Display Windows disk usage
      ansible.builtin.debug:
        var: disk_usage.stdout_lines
