---
- name: Configure Linux Servers
  hosts: linux
  become: yes
  tasks:
    - name: Stop and disable CUPS service
      ansible.builtin.systemd:
        name: cups
        state: stopped
        enabled: no

    - name: Configure firewalld rules
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
      loop:
        - "22"
        - "3389"

    - name: Reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded

- name: Configure Windows Servers
  hosts: windows
  tasks:
    - name: Disable Spooler service
      ansible.windows.win_service:
        name: Spooler
        state: stopped
        start_mode: disabled

    - name: Configure Windows Firewall
      ansible.windows.win_shell: |
        New-NetFirewallRule -DisplayName "Allow SSH" -Direction Inbound -LocalPort 22 -Protocol TCP -Action Allow
        New-NetFirewallRule -DisplayName "Allow RDP" -Direction Inbound -LocalPort 3389 -Protocol TCP -Action Allow
